steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'api'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aiqa', '.']
    id: build-backend-image

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aiqa']
    id: push-backend-image

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: fetch-secrets
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secrets..."
        CLIENT_ID=$(gcloud secrets versions access latest --secret=GOOGLE_CLIENT_ID)
        REDIRECT_URI=$(gcloud secrets versions access latest --secret=GOOGLE_REDIRECT_URI)
        echo "CLIENT_ID=$CLIENT_ID" > frontend.env
        echo "REDIRECT_URI=$REDIRECT_URI" >> frontend.env

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: build-frontend-image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLIENT_ID=$(gcloud secrets versions access latest --secret=GOOGLE_CLIENT_ID)
        REDIRECT_URI=$(gcloud secrets versions access latest --secret=GOOGLE_REDIRECT_URI)

        echo "Building frontend with secrets..."
        docker build --build-arg NEXT_PUBLIC_CLIENT_ID="$CLIENT_ID" --build-arg NEXT_PUBLIC_REDIRECT_URI="$REDIRECT_URI" -t gcr.io/$PROJECT_ID/aiqa-frontend client

        echo "Pushing image..."
        docker push gcr.io/$PROJECT_ID/aiqa-frontend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aiqa-frontend']
    id: push-frontend-image
    waitFor: ['build-frontend-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create aiqa-release-$SHORT_SHA \
          --project=$PROJECT_ID \
          --region=europe-central2 \
          --delivery-pipeline=aiqa-pipeline \
          --skaffold-file=infra/skaffold.yaml \
          --images=backend=gcr.io/$PROJECT_ID/aiqa
    waitFor: ['push-backend-image']
    id: create-release

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy aiqa-frontend \
          --image gcr.io/$PROJECT_ID/aiqa-frontend \
          --region=europe-central2 \
          --platform=managed \
          --allow-unauthenticated
    id: deploy-frontend
    waitFor: ['push-frontend-image']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
