availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_REDIRECT_URI/versions/latest
      env: GOOGLE_REDIRECT_URI

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'api'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aiqa', '.']
    id: build-backend-image

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aiqa']
    id: push-backend-image

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    id: build-frontend-image
    secretEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_REDIRECT_URI']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting Docker build with secrets from Secret Manager..."
        docker build \
          --build-arg NEXT_PUBLIC_CLIENT_ID=$${GOOGLE_CLIENT_ID} \
          --build-arg NEXT_PUBLIC_REDIRECT_URI=$${GOOGLE_REDIRECT_URI} \
          -t gcr.io/$PROJECT_ID/aiqa-frontend .
        docker push gcr.io/$PROJECT_ID/aiqa-frontend

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create aiqa-release-$SHORT_SHA \
          --project=$PROJECT_ID \
          --region=europe-central2 \
          --delivery-pipeline=aiqa-pipeline \
          --skaffold-file=infra/skaffold.yaml \
          --images=backend=gcr.io/$PROJECT_ID/aiqa
    waitFor: ['push-backend-image']
    id: create-release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy aiqa-frontend \
          --image gcr.io/$PROJECT_ID/aiqa-frontend \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
    id: deploy-frontend
    waitFor: ['build-frontend-image']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
