steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   dir: 'api'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/aiqa', '.']
  #   id: build-backend-image

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/aiqa']
  #   id: push-backend-image

  # - name: 'gcr.io/cloud-builders/docker'
  #   dir: 'client'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/aiqa-frontend', '.']
  #   id: build-frontend-image

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/aiqa-frontend']
  #   id: push-frontend-image

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create aiqa-release-$SHORT_SHA \
          --project=$PROJECT_ID \
          --region=europe-central2 \
          --delivery-pipeline=aiqa-pipeline \
          --skaffold-file=infra/skaffold.yaml \
          --images=backend=gcr.io/$PROJECT_ID/aiqa,frontend=gcr.io/$PROJECT_ID/aiqa-frontend
    # waitFor: ['push-backend-image']
    id: create-release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy aiqa-frontend \
          --image gcr.io/$PROJECT_ID/aiqa-frontend \
          --region=europe-central2 \
          --platform=managed \
          --allow-unauthenticated
    id: deploy-frontend
    # waitFor: ['push-frontend-image']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
