apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: aiqa-pipeline
description: Pipeline to deploy AIQA backend
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
