apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: aiqa

build:
  artifacts:
    - image: gcr.io/plated-reducer-458308-d9/aiqa-backend
      context: api
    - image: gcr.io/plated-reducer-458308-d9/aiqa-frontend
      context: frontend

deploy:
  kubectl:
    manifests:
      - ./k8s/*
