apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: aiqa
build:
  artifacts:
    - image: gcr.io/plated-reducer-458308-d9/aiqa
      context: api
deploy:
  kubectl:
    manifests:
      - ./k8s/*
profiles:
  - name: target-1
    deploy:
      kubectl:
        manifests:
          - ./k8s/*