apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment
gke:
  cluster: projects/plated-reducer-458308-d9/locations/europe-central2/clusters/autopilot-cluster-1
