apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    networking.gke.io/managed-certificates: my-cert
    kubernetes.io/ingress.global-static-ip-name: my-static-ip
spec:
  defaultBackend:
    service:
      name: backend
      port:
        number: 80
  rules:
    - host: api.detect.uno
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
