apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  defaultBackend:
    service:
      name: backend
      port:
        number: 80
